version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Веб-интерфейс управления RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  auth_service:
    build:
      context: ./auth_service
      dockerfile: ./Dockerfile
    container_name: auth_service
    ports:
      - "8003:8003"
    environment:
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_NAME: AuthDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./auth_service:/app
    depends_on:
      - auth_db
      - rabbitmq

  auth_db:
    image: postgres:15.3
    container_name: auth_db
    environment:
      POSTGRES_DB: AuthDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data



  post_service:
    build:
      context: ./post_service
      dockerfile: ./Dockerfile
    container_name: post_service
    ports:
      - "8006:8006"
    environment:
      DB_HOST: post_db
      DB_PORT: 5432
      DB_NAME: PostDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./post_service:/app
    depends_on:
      - rabbitmq
      - post_db

  post_db:
    image: postgres:15.3
    container_name: post_db
    environment:
      POSTGRES_DB: PostDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data



  subscription_service:
    build:
      context: ./subscription_service
      dockerfile: ./Dockerfile
    container_name: subscription_service
    ports:
      - "8007:8007"
    environment:
      DB_HOST: subscription_db
      DB_PORT: 5432
      DB_NAME: SubscriptionDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./subscription_service:/app
    depends_on:
      - subscription_db
      - rabbitmq

  subscription_db:
    image: postgres:15.3
    container_name: subscription_db
    environment:
      POSTGRES_DB: SubscriptionDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - subscription_db_data:/var/lib/postgresql/data


  nginx:
     image: nginx:latest
     container_name: nginx
     ports:
       - "80:80"
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
       - auth_service
       - post_service
       - subscription_service
       - admin_service


  admin_service:
         build:
           context: ./admin_service
           dockerfile: ./admin.Dockerfile
         container_name: admin_service
         ports:
           - "8009:8009"
         environment:
           DB_HOST: admin_db
           DB_PORT: 5432
           DB_NAME: AdminDB
           DB_USER: postgres
           DB_PASSWORD: postgres
           RABBITMQ_HOST: rabbitmq
           RABBITMQ_PORT: 5672
         volumes:
           - ./admin_service:/app
         depends_on:
           - admin_db
           - rabbitmq

  admin_db:
         image: postgres:15.3
         container_name: admin_db
         environment:
           POSTGRES_DB: AdminDB
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
         ports:
           - "5436:5432"
         volumes:
           - admin_db_data:/var/lib/postgresql/data



volumes:
  auth_db_data:
  post_db_data:
  subscription_db_data:
  rabbitmq_data:
  admin_db_data:
